project:
  type: website
  output-dir: _site

website:
  title: "Divvy Bike Analysis"
  site-url: https://divvy-bike-analysis.netlify.app
  repo-url: https://github.com/SadeekFarhan21/Divvy_Bike_Analysis
  bread-crumbs: true
  navbar:
    right:
      - icon: "github"
        href: https://github.com/SadeekFarhan21/Divvy_Bike_Analysis