project:
  type: website
  output-dir: _site

website:
  title: "Divvy Bike Analysis"
  site-url: https://divvy-bike-analysis.netlify.app
  repo-url: https://github.com/SadeekFarhan21/Divvy_Bike_Analysis
  favicon: Divvy_Logo.png
  navbar:
    right:
      - icon: "github"
        href: https://github.com/SadeekFarhan21/Divvy_Bike_Analysis
      - icon: "linkedin"
        href: https://www.linkedin.com/in/farhansadeekde110/
      - icon: "twitter"
        href: https://twitter.com/SadeekFarhan21