cookie_consent:
  style: simple
  type: express
  palette: light
  lang: en
  cookies_policy: https://example.com/cookies-policy
 
project:
    type: website

website:
    title: "My Website"
    navbar:
        right:
            - index.qmd
            - about.qmd