---
title: "Notebook"
output: 
    flexdashboard::flex_dashboard:
        orientation: columns
        vertical_layout: fill
date: "2025-01-18"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, importing-libraries}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(ggplot2)
library(webr)
library(flexdashboard)
```

```{r, reading-data}
january <- read.csv("datasets/202401-divvy-tripdata.csv")
february <- read.csv("datasets/202402-divvy-tripdata.csv")
march <- read.csv("datasets/202403-divvy-tripdata.csv")
april <- read.csv("datasets/202404-divvy-tripdata.csv")
may <- read.csv("datasets/202405-divvy-tripdata.csv")
june <- read.csv("datasets/202406-divvy-tripdata.csv")
july <- read.csv("datasets/202407-divvy-tripdata.csv")
august <- read.csv("datasets/202408-divvy-tripdata.csv")
september <- read.csv("datasets/202409-divvy-tripdata.csv")
october <- read.csv("datasets/202410-divvy-tripdata.csv")
november <- read.csv("datasets/202411-divvy-tripdata.csv")
december <- read.csv("datasets/202412-divvy-tripdata.csv")
```

```{r}
all_data <- bind_rows(
    january |> mutate(month = 1),
    february |> mutate(month = 2),
    march |> mutate(month = 3),
    april |> mutate(month = 4),
    may |> mutate(month = 5),
    june |> mutate(month = 6),
    july |> mutate(month = 7),
    august |> mutate(month = 8),
    september |> mutate(month = 9),
    october |> mutate(month = 10),
    november |> mutate(month = 11),
    december |> mutate(month = 12)
)
```

```{r, sample_dataset}
all_data <- all_data |> 
    sample_n(1000)
```


```{r, combining-data}
all_data <- all_data |>
      mutate(hour = hour(started_at)) |>
      mutate(time_of_day = 
      case_when (
            hour %in% 0:5 ~ "Night",
            hour %in% 6:11 ~ "Morning",
            hour %in% 12:17 ~ "Afternoon",
            hour %in% 18:23 ~ "Evening"
        )
)

all_data <- all_data |> 
    mutate(season = 
    case_when (
        month %in% c(12, 1, 2) ~ "Winter",
        month %in% c(3, 4, 5) ~ "Spring",
        month %in% c(6, 7, 8) ~ "Summer",
        month %in% c(9, 10, 11) ~ "Fall"
    )
)
sample_data <- all_data |> 
    sample_n(1000)
```



```{r}
rm(january, february, march, april, may, june, july, august, september, october, november, december)
```


```{r, ride_type_by_user}
ride_type_by_user <- sample_data |>
    group_by(member_casual) |>
    summarise(count = n()) |>
    mutate(
        proportion = count / sum(count),
        percentage = count / sum(count) * 100,
    )

ride_type_by_user |>
    mutate(
        start = lag(proportion, default = 0) * 2 * pi,
        end = cumsum(proportion) * 2 * pi,
    ) |>
    ggplot() +
    ggforce::geom_arc_bar(
        aes(
            x0 = 0, y0 = 0,
            r0 = 0.7, r = 1,
            start = start, 
            end = end,
            fill = member_casual 
        )
    ) +
    annotate(
      'text',  
      x = 0,
      y = 0,
      label = paste0(round(nrow(sample_data) / 1000000, 2), "M\nTotal\nRides"),
      family= "Arial",
      size = 7,
      lineheight = 1
    ) +
    coord_equal(expand = FALSE, xlim = c(-1.1, 1.1), ylim = c(-1.1, 1.1)) +
    theme_void(base_size = 16, base_family = 'Arial') +
    labs(
        fill = element_blank()
    ) +
    theme(
      legend.position = "none",
        legend.margin = margin(t = 1, b = 0.5, unit = 'cm'), 
    ) +
    scale_fill_manual(values = c("member" = "#1f77b4", "casual" = "#ff7f0e"))
```

```{r, ride_type_by_rideable}
ride_type_by_rideable <- sample_data |>
  group_by(rideable_type, member_casual) |>
  summarise(count = n())
ride_type_by_rideable
ggplot(ride_type_by_rideable, aes(x = rideable_type, y = count, fill = member_casual)) +
  geom_bar(stat = "identity", position = "stack") +
  labs(
  title = "Ride Type by Bike Type",
  x = "Bike Type",
  y = "Count",
  fill = "User Type"
  ) +
  theme_minimal()
```

```{r, average_ride_length}
average_ride_length <- sample_data |>
    mutate(ride_length = as.numeric(difftime(ended_at, started_at, units = "mins"))) |>
    group_by(member_casual) |>
    summarise(average_ride_length = mean(ride_length, na.rm = TRUE))
average_ride_length
```

```{r, ride_length_by_weekday}
ride_length_by_weekday <- sample_data |>
    mutate(ride_length = as.numeric(difftime(ended_at, started_at, units = "mins")),
           day_of_week = weekdays(as.Date(started_at))) |>
    group_by(day_of_week) |>
    summarise(average_ride_length = mean(ride_length, na.rm = TRUE)) |>
    mutate(day_of_week = fct_relevel(day_of_week, c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")))


ggplot(ride_length_by_weekday, aes(x = day_of_week, y = average_ride_length)) +
    geom_bar(stat = "identity", width=0.2) +
    labs(
        title = "Average Ride Length by Day of the Week",
        x = "Day of the Week",
        y = "Average Ride Length (minutes)"
    ) +
    theme_minimal()
```

```{r, total_rides_by_weekday}
total_rides_by_weekday <- sample_data |>
    mutate(day_of_week = weekdays(as.Date(started_at))) |>
    group_by(day_of_week) |>
    summarise(total_rides = n()) |>
    mutate(day_of_week = fct_relevel(day_of_week, c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")))
total_rides_by_weekday |>
    ggplot(aes(x = day_of_week, y = total_rides)) +
    geom_bar(stat = "identity") +
    labs(
        title = "Total Rides by Day of the Week",
        x = "Day of the Week",
        y = "Total Rides"
    ) +
    theme_minimal()
```

```{r, total_rides_by_hour}
total_rides_by_hour <- sample_data |>
    mutate(hour = hour(started_at)) |>
    group_by(hour, time_of_day) |>
    summarise(total_rides = n())

total_rides_by_hour |>
    ggplot(aes(x = hour, y = total_rides, fill=time_of_day)) +
    geom_bar(stat = "identity") +
    labs(
        title = "Total Rides by Hour of the Day",
        x = "Hour of the Day",
        y = "Total Rides"
    ) +
    theme_minimal()
```


```{r, total_rides_by_month}
total_rides_by_month <- sample_data |>
  mutate(month = month(started_at, label = TRUE)) |>
  group_by(month, season) |>
  summarise(total_rides = n())
total_rides_by_month

total_rides_by_month |>
  ggplot(aes(x = month, y = total_rides, fill=season)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Total Rides by Month",
    x = "Month",
    y = "Total Rides",
  ) +
  theme_minimal()
```

```{r}

```


